c_SRC_FILES += \
	lv_charging_case/lv_frame/custom/custom.c \
	lv_charging_case/lv_frame/custom/lv_demo_alarm/alarm_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_alarm/lv_demo_alarm.c \
	lv_charging_case/lv_frame/custom/lv_demo_alarm/lv_demo_alarm_ring.c \
	lv_charging_case/lv_frame/custom/lv_demo_anc/lv_demo_anc.c \
	lv_charging_case/lv_frame/custom/lv_demo_brightness/lv_demo_brightness.c \
	lv_charging_case/lv_frame/custom/lv_demo_call/lv_demo_call.c \
	lv_charging_case/lv_frame/custom/lv_demo_charging/lv_demo_charging.c \
	lv_charging_case/lv_frame/custom/lv_demo_equalizer/lv_demo_equalizer.c \
	lv_charging_case/lv_frame/custom/lv_demo_findmy/lv_demo_findmy.c \
	lv_charging_case/lv_frame/custom/lv_demo_json/lv_demo_json.c \
	lv_charging_case/lv_frame/custom/lv_demo_language/lv_demo_language.c \
	lv_charging_case/lv_frame/custom/lv_demo_light/lv_demo_light.c \
	lv_charging_case/lv_frame/custom/lv_demo_lock/lv_demo_lock.c \
	lv_charging_case/lv_frame/custom/lv_demo_low_rle_animing/low_rle_animing.c \
	lv_charging_case/lv_frame/custom/lv_demo_menu/lv_demo_menu.c \
	lv_charging_case/lv_frame/custom/lv_demo_multilingual/lv_demo_multilingual.c \
	lv_charging_case/lv_frame/custom/lv_demo_music/lv_demo_music.c \
	lv_charging_case/lv_frame/custom/lv_demo_music/sd_music_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_pc_mode/lv_demo_pc_mode.c \
	lv_charging_case/lv_frame/custom/lv_demo_pop_up/lv_demo_pop_up.c \
	lv_charging_case/lv_frame/custom/lv_demo_poweroff/lv_demo_poweroff.c \
	lv_charging_case/lv_frame/custom/lv_demo_poweron/lv_demo_poweron.c \
	lv_charging_case/lv_frame/custom/lv_demo_product_test/lv_demo_product_test.c \
	lv_charging_case/lv_frame/custom/lv_demo_product_test/product_test_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_snap/lv_demo_snap.c \
	lv_charging_case/lv_frame/custom/lv_demo_snap/snap_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_soc/soc.c \
	lv_charging_case/lv_frame/custom/lv_demo_squelch/lv_demo_squelch.c \
	lv_charging_case/lv_frame/custom/lv_demo_status_bar/lv_demo_status_bar_bottom.c \
	lv_charging_case/lv_frame/custom/lv_demo_status_bar/lv_demo_status_bar_top.c \
	lv_charging_case/lv_frame/custom/lv_demo_tiktok/lv_demo_tiktok.c \
	lv_charging_case/lv_frame/custom/lv_demo_tiktok/tiktok_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_time/lv_demo_time.c \
	lv_charging_case/lv_frame/custom/lv_demo_time/time_api.c \
	lv_charging_case/lv_frame/custom/lv_demo_upgrade/lv_demo_upgrade.c \
	lv_charging_case/lv_frame/custom/lv_demo_volume/lv_demo_volume.c \
	lv_charging_case/lv_frame/custom/lv_demo_wallpaper/lv_demo_wallpaper.c \
	lv_charging_case/lv_frame/custom/lv_demo_weather/lv_demo_weather.c \
	lv_charging_case/lv_frame/custom/lv_demo_wooden_fish/lv_demo_wooden_fish.c \
	lv_charging_case/lv_frame/custom/math/math_function.c \
	lv_charging_case/lv_frame/custom/message/ui_msg_action.c \
	lv_charging_case/lv_frame/custom/screen_loop_manager/PageManager.c \
	lv_charging_case/lv_frame/custom/screen_loop_manager/lv_demo_screen_loop.c \
	lv_charging_case/lv_frame/custom/screen_loop_manager/page_adapter.c \
	lv_charging_case/lv_frame/custom/system/device_refresh_control.c \
	lv_charging_case/lv_frame/custom/system/device_sleep_control.c \

INCLUDES += \
	-Ilv_charging_case/lv_frame/custom/lv_demo_alarm \
	-Ilv_charging_case/lv_frame/custom/lv_demo_anc \
	-Ilv_charging_case/lv_frame/custom/lv_demo_brightness \
	-Ilv_charging_case/lv_frame/custom/lv_demo_call \
	-Ilv_charging_case/lv_frame/custom/lv_demo_charging \
	-Ilv_charging_case/lv_frame/custom/lv_demo_equalizer \
	-Ilv_charging_case/lv_frame/custom/lv_demo_findmy \
	-Ilv_charging_case/lv_frame/custom/lv_demo_json \
	-Ilv_charging_case/lv_frame/custom/lv_demo_language \
	-Ilv_charging_case/lv_frame/custom/lv_demo_light \
	-Ilv_charging_case/lv_frame/custom/lv_demo_lock \
	-Ilv_charging_case/lv_frame/custom/lv_demo_low_rle_animing \
	-Ilv_charging_case/lv_frame/custom/lv_demo_menu \
	-Ilv_charging_case/lv_frame/custom/lv_demo_multilingual \
	-Ilv_charging_case/lv_frame/custom/lv_demo_music \
	-Ilv_charging_case/lv_frame/custom/lv_demo_pc_mode \
	-Ilv_charging_case/lv_frame/custom/lv_demo_pop_up \
	-Ilv_charging_case/lv_frame/custom/lv_demo_poweroff \
	-Ilv_charging_case/lv_frame/custom/lv_demo_poweron \
	-Ilv_charging_case/lv_frame/custom/lv_demo_product_test \
	-Ilv_charging_case/lv_frame/custom/lv_demo_snap \
	-Ilv_charging_case/lv_frame/custom/lv_demo_soc \
	-Ilv_charging_case/lv_frame/custom/lv_demo_squelch \
	-Ilv_charging_case/lv_frame/custom/lv_demo_status_bar \
	-Ilv_charging_case/lv_frame/custom/lv_demo_tiktok \
	-Ilv_charging_case/lv_frame/custom/lv_demo_time \
	-Ilv_charging_case/lv_frame/custom/lv_demo_upgrade \
	-Ilv_charging_case/lv_frame/custom/lv_demo_volume \
	-Ilv_charging_case/lv_frame/custom/lv_demo_wallpaper \
	-Ilv_charging_case/lv_frame/custom/lv_demo_weather \
	-Ilv_charging_case/lv_frame/custom/lv_demo_wooden_fish \
	-Ilv_charging_case/lv_frame/custom/math \
	-Ilv_charging_case/lv_frame/custom/message \
	-Ilv_charging_case/lv_frame/custom/screen_loop_manager \
	-Ilv_charging_case/lv_frame/custom/system \
	-Ilv_charging_case/lv_frame/custom \
