//generated by ResBuilder
#ifndef _RESULT_PIC_INDEX_H_  
#define _RESULT_PIC_INDEX_H_  

////BmpResID Define Table////

//PAGE 0
#define  PAGE0_5dad___IMAGES_TEMP1    0x000001 //  ./images/temp1.gif

#endif
