#include "app_config.h"
#include "audio_config.h"
#include "tone_player.h"

const char *tone_table[] = {
    [IDEX_TONE_NUM_0] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_1] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_2] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_3] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_4] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_5] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_6] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_7] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_8] 			= TONE_NORMAL,
    [IDEX_TONE_NUM_9] 			= TONE_NORMAL,
    [IDEX_TONE_BT_MODE] 		= TONE_NORMAL,
    [IDEX_TONE_BT_CONN] 		= TONE_NORMAL,
    [IDEX_TONE_BT_DISCONN] 		= TONE_NORMAL,
    [IDEX_TONE_TWS_CONN] 		= TONE_NORMAL,
    [IDEX_TONE_TWS_DISCONN]		= TONE_NORMAL,
    [IDEX_TONE_LOW_POWER] 		= TONE_NORMAL,
    [IDEX_TONE_POWER_OFF] 		= TONE_NORMAL,
    [IDEX_TONE_POWER_ON] 		= TONE_NORMAL,
    [IDEX_TONE_RING] 			= TONE_NORMAL,
    [IDEX_TONE_MAX_VOL] 		= TONE_NORMAL,
    [IDEX_TONE_NORMAL] 			= TONE_NORMAL,
    [IDEX_TONE_MUSIC] 			= TONE_NORMAL,
    [IDEX_TONE_LINEIN] 			= TONE_NORMAL,
    [IDEX_TONE_FM] 				= TONE_NORMAL,
    [IDEX_TONE_PC] 				= TONE_NORMAL,
    [IDEX_TONE_RTC] 			= TONE_NORMAL,
    [IDEX_TONE_RECORD] 			= TONE_NORMAL,
    [IDEX_TONE_UDISK] 			= TONE_NORMAL,
    [IDEX_TONE_SD] 				= TONE_NORMAL,
};

