c_SRC_FILES += \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_alpha16.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_argb.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_chroma_keyed.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_indexed16.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/img_benchmark_cogwheel_rgb565a8.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_12_compr_az.c.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_16_compr_az.c.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/assets/lv_font_bechmark_montserrat_28_compr_az.c.c \
	lv_charging_case/lv_frame/lvgl/demos/benchmark/lv_demo_benchmark.c \
	lv_charging_case/lv_frame/lvgl/demos/keypad_encoder/lv_demo_keypad_encoder.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_corner_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_loop.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_loop_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_next.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_next_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_pause.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_pause_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_play.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_play_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_prev.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_prev_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_corner_left.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_corner_left_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_corner_right.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_corner_right_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_1.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_1_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_2.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_2_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_3.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_cover_3_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_1.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_1_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_2.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_2_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_3.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_3_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_4.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_icon_4_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_list_border.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_list_border_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_logo.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_slider_knob.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_slider_knob_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_wave_top.c \
	lv_charging_case/lv_frame/lvgl/demos/music/assets/img_lv_demo_music_wave_top_large.c \
	lv_charging_case/lv_frame/lvgl/demos/music/lv_demo_music.c \
	lv_charging_case/lv_frame/lvgl/demos/music/lv_demo_music_list.c \
	lv_charging_case/lv_frame/lvgl/demos/music/lv_demo_music_main.c \
	lv_charging_case/lv_frame/lvgl/demos/stress/lv_demo_stress.c \
	lv_charging_case/lv_frame/lvgl/demos/widgets/assets/img_clothes.c \
	lv_charging_case/lv_frame/lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
	lv_charging_case/lv_frame/lvgl/demos/widgets/assets/img_lvgl_logo.c \
	lv_charging_case/lv_frame/lvgl/demos/widgets/lv_demo_widgets.c \
	lv_charging_case/lv_frame/lvgl/env_support/rt-thread/lv_rt_thread_port.c \
	lv_charging_case/lv_frame/lvgl/env_support/rt-thread/squareline/lv_ui_entry.c \
	lv_charging_case/lv_frame/lvgl/examples/anim/lv_example_anim_1.c \
	lv_charging_case/lv_frame/lvgl/examples/anim/lv_example_anim_2.c \
	lv_charging_case/lv_frame/lvgl/examples/anim/lv_example_anim_3.c \
	lv_charging_case/lv_frame/lvgl/examples/anim/lv_example_anim_timeline_1.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/animimg001.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/animimg002.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/animimg003.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/emoji/img_emoji_F617.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_caret_down.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_cogwheel_alpha16.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_cogwheel_argb.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_cogwheel_chroma_keyed.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_cogwheel_indexed16.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_cogwheel_rgb.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_hand.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_skew_strip.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/img_star.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/imgbtn_left.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/imgbtn_mid.c \
	lv_charging_case/lv_frame/lvgl/examples/assets/imgbtn_right.c \
	lv_charging_case/lv_frame/lvgl/examples/event/lv_example_event_1.c \
	lv_charging_case/lv_frame/lvgl/examples/event/lv_example_event_2.c \
	lv_charging_case/lv_frame/lvgl/examples/event/lv_example_event_3.c \
	lv_charging_case/lv_frame/lvgl/examples/event/lv_example_event_4.c \
	lv_charging_case/lv_frame/lvgl/examples/get_started/lv_example_get_started_1.c \
	lv_charging_case/lv_frame/lvgl/examples/get_started/lv_example_get_started_2.c \
	lv_charging_case/lv_frame/lvgl/examples/get_started/lv_example_get_started_3.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_1.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_2.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_3.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_4.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_5.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/flex/lv_example_flex_6.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_1.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_2.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_3.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_4.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_5.c \
	lv_charging_case/lv_frame/lvgl/examples/layouts/grid/lv_example_grid_6.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/bmp/lv_example_bmp_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/ffmpeg/lv_example_ffmpeg_2.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/freetype/lv_example_freetype_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/gif/img_bulb_gif.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/gif/lv_example_gif_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/png/img_wink_png.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/png/lv_example_png_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/qrcode/lv_example_qrcode_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/rlottie/lv_example_rlottie_1.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/rlottie/lv_example_rlottie_2.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/rlottie/lv_example_rlottie_approve.c \
	lv_charging_case/lv_frame/lvgl/examples/libs/sjpg/lv_example_sjpg_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/fragment/lv_example_fragment_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/fragment/lv_example_fragment_2.c \
	lv_charging_case/lv_frame/lvgl/examples/others/gridnav/lv_example_gridnav_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/gridnav/lv_example_gridnav_2.c \
	lv_charging_case/lv_frame/lvgl/examples/others/gridnav/lv_example_gridnav_3.c \
	lv_charging_case/lv_frame/lvgl/examples/others/gridnav/lv_example_gridnav_4.c \
	lv_charging_case/lv_frame/lvgl/examples/others/ime/lv_example_ime_pinyin_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/ime/lv_example_ime_pinyin_2.c \
	lv_charging_case/lv_frame/lvgl/examples/others/imgfont/lv_example_imgfont_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/monkey/lv_example_monkey_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/monkey/lv_example_monkey_2.c \
	lv_charging_case/lv_frame/lvgl/examples/others/monkey/lv_example_monkey_3.c \
	lv_charging_case/lv_frame/lvgl/examples/others/msg/lv_example_msg_1.c \
	lv_charging_case/lv_frame/lvgl/examples/others/msg/lv_example_msg_2.c \
	lv_charging_case/lv_frame/lvgl/examples/others/msg/lv_example_msg_3.c \
	lv_charging_case/lv_frame/lvgl/examples/others/snapshot/lv_example_snapshot_1.c \
	lv_charging_case/lv_frame/lvgl/examples/porting/lv_port_disp_template.c \
	lv_charging_case/lv_frame/lvgl/examples/porting/lv_port_fs_template.c \
	lv_charging_case/lv_frame/lvgl/examples/porting/lv_port_indev_template.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_1.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_2.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_3.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_4.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_5.c \
	lv_charging_case/lv_frame/lvgl/examples/scroll/lv_example_scroll_6.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_1.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_10.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_11.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_12.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_13.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_14.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_15.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_2.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_3.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_4.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_5.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_6.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_7.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_8.c \
	lv_charging_case/lv_frame/lvgl/examples/styles/lv_example_style_9.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/animimg/lv_example_animimg_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/arc/lv_example_arc_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/arc/lv_example_arc_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_5.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/bar/lv_example_bar_6.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btn/lv_example_btn_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btn/lv_example_btn_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btn/lv_example_btn_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/btnmatrix/lv_example_btnmatrix_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/calendar/lv_example_calendar_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/canvas/lv_example_canvas_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/canvas/lv_example_canvas_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_5.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_6.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_7.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_8.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/chart/lv_example_chart_9.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/checkbox/lv_example_checkbox_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/checkbox/lv_example_checkbox_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/colorwheel/lv_example_colorwheel_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/dropdown/lv_example_dropdown_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/dropdown/lv_example_dropdown_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/dropdown/lv_example_dropdown_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/img/lv_example_img_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/img/lv_example_img_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/img/lv_example_img_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/img/lv_example_img_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/imgbtn/lv_example_imgbtn_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/keyboard/lv_example_keyboard_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/label/lv_example_label_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/label/lv_example_label_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/label/lv_example_label_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/label/lv_example_label_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/label/lv_example_label_5.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/led/lv_example_led_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/line/lv_example_line_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/list/lv_example_list_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/list/lv_example_list_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/menu/lv_example_menu_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/menu/lv_example_menu_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/menu/lv_example_menu_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/menu/lv_example_menu_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/menu/lv_example_menu_5.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/meter/lv_example_meter_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/meter/lv_example_meter_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/meter/lv_example_meter_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/meter/lv_example_meter_4.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/msgbox/lv_example_msgbox_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/obj/lv_example_obj_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/obj/lv_example_obj_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/roller/lv_example_roller_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/roller/lv_example_roller_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/roller/lv_example_roller_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/slider/lv_example_slider_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/slider/lv_example_slider_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/slider/lv_example_slider_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/span/lv_example_span_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/spinbox/lv_example_spinbox_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/spinner/lv_example_spinner_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/switch/lv_example_switch_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/table/lv_example_table_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/table/lv_example_table_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/tabview/lv_example_tabview_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/tabview/lv_example_tabview_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/textarea/lv_example_textarea_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/textarea/lv_example_textarea_2.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/textarea/lv_example_textarea_3.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/tileview/lv_example_tileview_1.c \
	lv_charging_case/lv_frame/lvgl/examples/widgets/win/lv_example_win_1.c \
	lv_charging_case/lv_frame/lvgl/lvgl_main.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_disp.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_event.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_group.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_indev.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_indev_scroll.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_class.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_draw.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_pos.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_scroll.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_style.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_style_gen.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_obj_tree.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_refr.c \
	lv_charging_case/lv_frame/lvgl/src/core/lv_theme.c \
	lv_charging_case/lv_frame/lvgl/src/draw/arm2d/lv_gpu_arm2d.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_arc.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_img.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_label.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_layer.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_line.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_mask.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_rect.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_transform.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_draw_triangle.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_img_buf.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_img_cache.c \
	lv_charging_case/lv_frame/lvgl/src/draw/lv_img_decoder.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
	lv_charging_case/lv_frame/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_arc.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_bg.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_composite.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_img.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_label.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_layer.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_line.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_mask.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_rect.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sdl/lv_draw_sdl_utils.c \
	lv_charging_case/lv_frame/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_arc.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_blend.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_dither.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_img.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_layer.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_letter.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_line.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_rect.c \
	lv_charging_case/lv_frame/lvgl/src/draw/sw/lv_draw_sw_transform.c \
	lv_charging_case/lv_frame/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c \
	lv_charging_case/lv_frame/lvgl/src/extra/layouts/flex/lv_flex.c \
	lv_charging_case/lv_frame/lvgl/src/extra/layouts/grid/lv_grid.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/bmp/lv_bmp.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/freetype/lv_freetype.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/gif/gifdec.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/gif/lv_gif.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/png/lodepng.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/png/lv_png.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/qrcode/lv_qrcode.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/qrcode/qrcodegen.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/rlottie/lv_rlottie.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/sjpg/lv_sjpg.c \
	lv_charging_case/lv_frame/lvgl/src/extra/libs/sjpg/tjpgd.c \
	lv_charging_case/lv_frame/lvgl/src/extra/lv_extra.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/fragment/lv_fragment.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/fragment/lv_fragment_manager.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/gridnav/lv_gridnav.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/ime/lv_ime_pinyin.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/imgfont/lv_imgfont.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/monkey/lv_monkey.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/msg/lv_msg.c \
	lv_charging_case/lv_frame/lvgl/src/extra/others/snapshot/lv_snapshot.c \
	lv_charging_case/lv_frame/lvgl/src/extra/themes/basic/lv_theme_basic.c \
	lv_charging_case/lv_frame/lvgl/src/extra/themes/default/lv_theme_default.c \
	lv_charging_case/lv_frame/lvgl/src/extra/themes/mono/lv_theme_mono.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/animimg/lv_animimg.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/calendar/lv_calendar.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/chart/lv_chart.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/dclock/lv_dclock.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/led/lv_led.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/list/lv_list.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/menu/lv_menu.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/meter/lv_meter.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/span/lv_span.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/spinner/lv_spinner.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/tabview/lv_tabview.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/tileview/lv_tileview.c \
	lv_charging_case/lv_frame/lvgl/src/extra/widgets/win/lv_win.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_fmt_txt.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_loader.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_10.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_12.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_12_subpx.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_14.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_16.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_18.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_20.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_22.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_24.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_26.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_28.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_28_compressed.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_30.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_32.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_34.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_36.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_38.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_40.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_42.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_44.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_46.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_48.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_montserrat_8.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_simsun_16_cjk.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_unscii_16.c \
	lv_charging_case/lv_frame/lvgl/src/font/lv_font_unscii_8.c \
	lv_charging_case/lv_frame/lvgl/src/hal/lv_hal_disp.c \
	lv_charging_case/lv_frame/lvgl/src/hal/lv_hal_indev.c \
	lv_charging_case/lv_frame/lvgl/src/hal/lv_hal_tick.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_anim.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_anim_timeline.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_area.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_async.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_bidi.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_color.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_fs.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_gc.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_ll.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_log.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_lru.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_math.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_mem.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_printf.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_style.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_style_gen.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_templ.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_timer.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_tlsf.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_txt.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_txt_ap.c \
	lv_charging_case/lv_frame/lvgl/src/misc/lv_utils.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_arc.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_bar.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_btn.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_btnmatrix.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_canvas.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_checkbox.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_dropdown.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_img.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_label.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_line.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_objx_templ.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_roller.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_slider.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_switch.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_table.c \
	lv_charging_case/lv_frame/lvgl/src/widgets/lv_textarea.c \
	lv_charging_case/lv_frame/lvgl/tests/makefile/test.c \
	lv_charging_case/lv_frame/lvgl/tests/src/lv_test_indev.c \
	lv_charging_case/lv_frame/lvgl/tests/src/lv_test_init.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/_test_template.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_arc.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_bar.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_checkbox.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_config.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_demo_stress.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_demo_widgets.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_dropdown.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_event.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_font_loader.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_fs.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_line.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_mem.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_obj_tree.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_slider.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_snapshot.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_style.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_switch.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_table.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_textarea.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_cases/test_txt.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_fonts/font_1.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_fonts/font_2.c \
	lv_charging_case/lv_frame/lvgl/tests/src/test_fonts/font_3.c \
	lv_charging_case/lv_frame/lvgl/tests/unity/unity.c \
	lv_charging_case/lv_frame/lvgl/tests/unity/unity_support.c \

INCLUDES += \
	-Ilv_charging_case/lv_frame/lvgl \
	-Ilv_charging_case/lv_frame \
